const data = [
    { title: 'I was bringing humor to the room.', link: 'https:/\/docs.google.com/document/d/1EZZYQ4251VnAGsxuyWWp3HK5e2mQm-emNOR7NTGSJ80/preview?usp=sharing', slug: 'I-was-bringing-humor-to-the-room' },
    { title: 'Ambition, Duality, and Reality', link: 'https:/\/docs.google.com/document/d/13o8dvetnpMt4XgsgYa8fczunTcIm5RCbCjALQWx-mm4/preview?usp=sharing', slug: 'Ambition-Duality-and-Reality' },
    { title: 'The high working man', link: 'https:/\/docs.google.com/document/d/1zTVRpECpaG9RfEUdCVRy_vNwboXhXf0oAEwQeVBwTOk/preview?usp=sharing', slug: 'The-high-working-man' },
    { title: 'Cinema Afterlife', link: 'https:/\/docs.google.com/document/d/1qwNELkPVk2e9yy10-bvAVEQ7RYQ-ifq5Dt7HGW6x7N4/preview?usp=sharing', slug: 'Cinema-Afterlife' },
    { title: 'Riding in the back of her car', link: 'https:/\/docs.google.com/document/d/1KHg0-o7cddaxr1JOce2eSM74aqCr0XoVOAouZyLkvF0/preview?usp=sharing', slug: 'Riding-in-the-back-of-her-car' },
    { title: 'Attorney, Mechanic, Doctor', link: 'https:/\/docs.google.com/document/d/1szA-sVxkqHnc3hzS3CQj4SeSH3ApSVaqQEsXzm439bE/preview?usp=sharing', slug: 'Attorney-Mechanic-Doctor' },
    { title: 'The tailor and old eyes', link: 'https:/\/docs.google.com/document/d/1LQgDQDIGZIFaXnnnr9jxF9g63-C2p9brMT4V2iEhAEM/preview?usp=sharing', slug: 'The-tailor-and-old-eyes' },
    { title: 'In The Back of Jake\'s Truck Watching The Cinema Through The Topper', link: 'https:/\/docs.google.com/document/d/1oXOpDMIbrn1eyVL9f3T29f4UDzWw_vryy73feoIG0aI/preview?usp=sharing', slug: 'In-The-Back-of-Jakes-Truck-Watching-The-Cinema-Through-The-Topper' },
    { title: 'Feeling Whitney', link: 'https:/\/docs.google.com/document/d/1MMroZK5YHCb9_kaWuy6cSYp4FyqJPQBxrhXHaM9Udgo/preview?usp=sharing', slug: 'Feeling-Whitney' },
    { title: 'We Are Atoms', link: 'https:/\/docs.google.com/document/d/11Kani7yJHS6VFCZm-nzN1qciCLMDPjPhVFyquamPfBs/preview?usp=sharing', slug: 'We-Are-Atoms' },
    { title: 'Release the Fish Before it Dies', link: 'https:/\/docs.google.com/document/d/1ffQKYSvQ0JUpo2uX3P8BVr4-tpEXgo6lyUVVKQZwg4M/preview?usp=sharing', slug: 'Release-the-Fish-Before-it-Dies' },
    { title: 'Molting', link: 'https:/\/docs.google.com/document/d/1f4bPxbwMpJV7NstS2Y4jhHaO4TSiDW3V_Y2reO9dJR0/preview?usp=sharing', slug: 'Molting' },
    { title: 'Train Dream', link: 'https:/\/docs.google.com/document/d/1pXYbvxQBUJ3zcp0kwqcvuUKC0JRlFt9Aa6WAGaKSW44/preview?usp=sharing', slug: 'Train-Dream' },
    { title: 'The Wall Between Me and God', link: 'https:/\/docs.google.com/document/d/11KNXynuGwNIZX_9cF9TJ0a4RKFZqJtw8zw66Up5MyJg/preview?usp=sharing', slug: 'The-Wall-Between-Me-and-God' },
    { title: 'The Chairs for Decoration', link: 'https:/\/docs.google.com/document/d/1KZ8JpAafd2zX9Yb9uiZqhLE635fmx9YgKpuJbhrsyr8/preview?usp=sharing', slug: 'The-Chairs-for-Decoration' },
]